theme = "monokai"

[keys.normal]
#esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"
C-o = ":open ~/.config/helix/config.toml" # Ctrl+O to open the config
X = "extend_line_above" # Shift+x to select the whole line above
D = ["goto_first_nonwhitespace", "extend_to_line_end", "change_selection"] # Wipe and edit the current line
c = ["trim_selections", "change_selection"] # Make 'c' automatically strip the selection of extra whitespace
a = ["append_mode", "collapse_selection"] # Remove the selection when entering insert mode with 'a'
"tab" = "goto_next_function" # Select and jump to the next function via Treesitter
"S-tab" = "goto_prev_function" # Select and jump to the previous function via Treesitter

[keys.insert]
j = { j = "normal_mode" }
