theme = "monokai"

[editor]
auto-format = false
line-number = "relative"
gutters = ["diagnostics", "spacer", "line-numbers"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
0 = "goto_line_start"
X = "extend_line_above" # Shift+x to select the whole line above
D = ["extend_to_line_end", "change_selection"] # Wipe until end of line and edit
c = ["trim_selections", "change_selection"] # Make 'c' automatically strip the selection of extra whitespace
a = ["append_mode", "collapse_selection"] # Remove the selection when entering insert mode with 'a'
"tab" = "goto_next_function" # Select and jump to the next function via Treesitter
"S-tab" = "goto_prev_function" # Select and jump to the previous function via Treesitter

[keys.insert]
j = { j = "normal_mode" }
