[[language]]
name = "elixir"
scope = "source.elixir"
language-servers = [{ name = "nextls", except-features = ["diagnostics"] }]

[language-server.nextls]
command = "/home/malte/local/bin/next-ls"
args = ["--stdio=true"]
config = { experimental = { completions = { enable = true } } }
