[[language]]
name = "elixir"
scope = "source.elixir"
language-servers = [{ name = "next-ls", except-features = ["diagnostics"] }]

[language-server.next-ls]
command = "next-ls"
args = ["--stdio=true"]
config = { experimental = { completions = { enable = true } } }

# [language-server.elixir-ls]
# command = "elixir-ls"
